### ISSUE TITLE
menu navegacion menus

### ISSUE THREAD

**Issue by cristiankode** [DemianEros/PruebaTecnicaNexen#1]
Agregar el menu de menus:

![image](https://github.com/DemianEros/PruebaTecnicaNexen/assets/29128795/72c99836-2505-461b-a4f3-9675741eb7be)

[evaluación_técnica_filtro_1.pdf](https://github.com/user-attachments/files/16181117/evaluacion_tecnica_filtro_1.pdf)

**Comment by DemianEros** [comment]
task terminada
